version: '3'

services:
  user_server:
    build:
      context: ./userServer
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"
    networks:
      - app-network

  chat_server:
    build:
      context: ./chatServer
    volumes:
      - ./data:/data
    ports:
      - "8001:8001"
    networks:
      - app-network

volumes:
  data:
      
networks:
  app-network:
    driver: bridge
